--CREATE MY USER 'alain'
--DROP USER alain CASCADE;
CREATE USER alain IDENTIFIED BY alain;
GRANT CREATE SESSION TO alain;
SELECT USERNAME FROM dba_users;

--DROP TABLESPACE 
--DROP TABLESPACE  alain_space

--CREATE A NEW PERSONAL alain_space TABLESPACE 
CREATE TABLESPACE alain_space
DATAFILE 'C:\ORACLE_BDD11G\app\oracle\oradata\XE\alain_space.dbf'
SIZE 50m;

--CHECK IF TABLE_SPACE HAS BEEN CREATED
SELECT * FROM SYS.DBA_DATA_FILES WHERE TABLESPACE_NAME LIKE '%ALAIN%';

--GRANT PERMISSION ON TABLESPACE
ALTER USER alain QUOTA UNLIMITED ON  alain_space;
GRANT UNLIMITED TABLESPACE  TO alain;

-- --GRANT ALL PRIVILIEGE TO alain
ALTER USER "ALAIN"
DEFAULT TABLESPACE "ALAIN_SPACE"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "ALAIN" QUOTA UNLIMITED ON ALAIN_SPACE;

-- ROLES
ALTER USER "ALAIN" DEFAULT ROLE "DATAPUMP_EXP_FULL_DATABASE","DBA","HS_ADMIN_EXECUTE_ROLE","ADM_PARALLEL_EXECUTE_TASK","CTXAPP","SELECT_CATALOG_ROLE","CONNECT","DATAPUMP_IMP_FULL_DATABASE","OEM_MONITOR","APEX_ADMINISTRATOR_ROLE","AQ_USER_ROLE","SCHEDULER_ADMIN","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","DBFS_ROLE","XDB_WEBSERVICES_OVER_HTTP","HS_ADMIN_SELECT_ROLE","PLUSTRACE","RESOURCE","AQ_ADMINISTRATOR_ROLE","DELETE_CATALOG_ROLE","XDB_WEBSERVICES_WITH_PUBLIC","XDB_WEBSERVICES","EXECUTE_CATALOG_ROLE","EXP_FULL_DATABASE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","AUTHENTICATEDUSER","OEM_ADVISOR","HS_ADMIN_ROLE","XDBADMIN","IMP_FULL_DATABASE";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "ALAIN" ;
GRANT DROP ANY CONTEXT TO "ALAIN" ;
GRANT UPDATE ANY CUBE TO "ALAIN" ;
GRANT DROP ANY TRIGGER TO "ALAIN" ;
GRANT MANAGE ANY FILE GROUP TO "ALAIN" ;
GRANT ALTER PUBLIC DATABASE LINK TO "ALAIN" ;
GRANT MANAGE FILE GROUP TO "ALAIN" ;
GRANT ALTER ANY INDEX TO "ALAIN" ;
GRANT DROP ANY SEQUENCE TO "ALAIN" ;
GRANT ALTER PROFILE TO "ALAIN" ;
GRANT UNDER ANY TABLE TO "ALAIN" ;
GRANT CREATE ASSEMBLY TO "ALAIN" ;
GRANT DROP ANY LIBRARY TO "ALAIN" ;
GRANT ALTER ANY EDITION TO "ALAIN" ;
GRANT CREATE ROLE TO "ALAIN" ;
GRANT CREATE LIBRARY TO "ALAIN" ;
GRANT DROP ROLLBACK SEGMENT TO "ALAIN" ;
GRANT CREATE TRIGGER TO "ALAIN" ;
GRANT ALTER ANY PROCEDURE TO "ALAIN" ;
GRANT ADMINISTER DATABASE TRIGGER TO "ALAIN" ;
GRANT DROP ANY MEASURE FOLDER TO "ALAIN" ;
GRANT CREATE ANY PROCEDURE TO "ALAIN" ;
GRANT ALTER ANY OUTLINE TO "ALAIN" ;
GRANT EXECUTE ANY INDEXTYPE TO "ALAIN" ;
GRANT CREATE ANY DIRECTORY TO "ALAIN" ;
GRANT ALTER ANY RULE SET TO "ALAIN" ;
GRANT ALTER ANY MINING MODEL TO "ALAIN" ;
GRANT DEBUG CONNECT SESSION TO "ALAIN" ;
GRANT CREATE ANY MINING MODEL TO "ALAIN" ;
GRANT ALTER SESSION TO "ALAIN" ;
GRANT CREATE MATERIALIZED VIEW TO "ALAIN" ;
GRANT MERGE ANY VIEW TO "ALAIN" ;
GRANT CREATE ANY INDEX TO "ALAIN" ;
GRANT CREATE DIMENSION TO "ALAIN" ;
GRANT EXECUTE ANY RULE SET TO "ALAIN" ;
GRANT ALTER ANY MATERIALIZED VIEW TO "ALAIN" ;
GRANT AUDIT SYSTEM TO "ALAIN" ;
GRANT CREATE OPERATOR TO "ALAIN" ;
GRANT MANAGE ANY QUEUE TO "ALAIN" ;
GRANT ALTER ANY SQL PROFILE TO "ALAIN" ;
GRANT GRANT ANY OBJECT PRIVILEGE TO "ALAIN" ;
GRANT CREATE INDEXTYPE TO "ALAIN" ;
GRANT AUDIT ANY TO "ALAIN" ;
GRANT DEBUG ANY PROCEDURE TO "ALAIN" ;
GRANT CREATE ANY MEASURE FOLDER TO "ALAIN" ;
GRANT CREATE ANY SEQUENCE TO "ALAIN" ;
GRANT CREATE MEASURE FOLDER TO "ALAIN" ;
GRANT UPDATE ANY CUBE BUILD PROCESS TO "ALAIN" ;
GRANT CREATE VIEW TO "ALAIN" ;
GRANT ALTER DATABASE LINK TO "ALAIN" ;
GRANT ALTER ANY ASSEMBLY TO "ALAIN" ;
GRANT CREATE ANY EVALUATION CONTEXT TO "ALAIN" ;
GRANT SELECT ANY MINING MODEL TO "ALAIN" ;
GRANT DELETE ANY CUBE DIMENSION TO "ALAIN" ;
GRANT ALTER ANY TABLE TO "ALAIN" ;
GRANT CREATE RULE TO "ALAIN" ;
GRANT BECOME USER TO "ALAIN" ;
GRANT SELECT ANY TABLE TO "ALAIN" ;
GRANT INSERT ANY MEASURE FOLDER TO "ALAIN" ;
GRANT CREATE ANY SQL PROFILE TO "ALAIN" ;
GRANT FORCE ANY TRANSACTION TO "ALAIN" ;
GRANT DELETE ANY TABLE TO "ALAIN" ;
GRANT ALTER ANY SEQUENCE TO "ALAIN" ;
GRANT SELECT ANY CUBE DIMENSION TO "ALAIN" ;
GRANT CREATE ANY EDITION TO "ALAIN" ;
GRANT CREATE EXTERNAL JOB TO "ALAIN" ;
GRANT DROP ANY MATERIALIZED VIEW TO "ALAIN" ;
GRANT CREATE ANY CUBE BUILD PROCESS TO "ALAIN" ;
GRANT FLASHBACK ANY TABLE TO "ALAIN" ;
GRANT DROP ANY RULE SET TO "ALAIN" ;
GRANT BACKUP ANY TABLE TO "ALAIN" ;
GRANT ALTER ANY CUBE TO "ALAIN" ;
GRANT CREATE TABLE TO "ALAIN" ;
GRANT EXECUTE ANY LIBRARY TO "ALAIN" ;
GRANT DROP ANY OUTLINE TO "ALAIN" ;
GRANT EXECUTE ASSEMBLY TO "ALAIN" ;
GRANT CREATE ANY DIMENSION TO "ALAIN" ;
GRANT DROP ANY TABLE TO "ALAIN" ;
GRANT ALTER ANY CLUSTER TO "ALAIN" ;
GRANT EXECUTE ANY CLASS TO "ALAIN" ;
GRANT DROP ANY DIMENSION TO "ALAIN" ;
GRANT CREATE ANY RULE SET TO "ALAIN" ;
GRANT SELECT ANY SEQUENCE TO "ALAIN" ;
GRANT UNDER ANY TYPE TO "ALAIN" ;
GRANT MANAGE TABLESPACE TO "ALAIN" ;
GRANT DROP ANY OPERATOR TO "ALAIN" ;
GRANT CREATE ANY OPERATOR TO "ALAIN" ;
GRANT EXEMPT IDENTITY POLICY TO "ALAIN" ;
GRANT CREATE TYPE TO "ALAIN" ;
GRANT CREATE TABLESPACE TO "ALAIN" ;
GRANT SELECT ANY TRANSACTION TO "ALAIN" ;
GRANT DELETE ANY MEASURE FOLDER TO "ALAIN" ;
GRANT CREATE ANY CUBE TO "ALAIN" ;
GRANT LOCK ANY TABLE TO "ALAIN" ;
GRANT CREATE EVALUATION CONTEXT TO "ALAIN" ;
GRANT DROP ANY TYPE TO "ALAIN" ;
GRANT ADVISOR TO "ALAIN" ;
GRANT CREATE PUBLIC DATABASE LINK TO "ALAIN" ;
GRANT ANALYZE ANY TO "ALAIN" ;
GRANT DROP ANY RULE TO "ALAIN" ;
GRANT INSERT ANY CUBE DIMENSION TO "ALAIN" ;
GRANT CREATE ROLLBACK SEGMENT TO "ALAIN" ;
GRANT CREATE ANY JOB TO "ALAIN" ;
GRANT ALTER USER TO "ALAIN" ;
GRANT QUERY REWRITE TO "ALAIN" ;
GRANT SELECT ANY DICTIONARY TO "ALAIN" ;
GRANT CREATE PUBLIC SYNONYM TO "ALAIN" ;
GRANT GLOBAL QUERY REWRITE TO "ALAIN" ;
GRANT ALTER ANY CUBE DIMENSION TO "ALAIN" ;
GRANT CREATE ANY CUBE DIMENSION TO "ALAIN" ;
GRANT DROP ANY CLUSTER TO "ALAIN" ;
GRANT CREATE ANY RULE TO "ALAIN" ;
GRANT UPDATE ANY CUBE DIMENSION TO "ALAIN" ;
GRANT SYSDBA TO "ALAIN" ;
GRANT ADMINISTER RESOURCE MANAGER TO "ALAIN" ;
GRANT CREATE ANY SYNONYM TO "ALAIN" ;
GRANT DROP ANY SYNONYM TO "ALAIN" ;
GRANT DROP ANY MINING MODEL TO "ALAIN" ;
GRANT EXECUTE ANY PROCEDURE TO "ALAIN" ;
GRANT CREATE SYNONYM TO "ALAIN" ;
GRANT EXECUTE ANY PROGRAM TO "ALAIN" ;
GRANT EXECUTE ANY TYPE TO "ALAIN" ;
GRANT ON COMMIT REFRESH TO "ALAIN" ;
GRANT CREATE SEQUENCE TO "ALAIN" ;
GRANT COMMENT ANY MINING MODEL TO "ALAIN" ;
GRANT ADMINISTER SQL TUNING SET TO "ALAIN" ;
GRANT SYSOPER TO "ALAIN" ;
GRANT CREATE ANY INDEXTYPE TO "ALAIN" ;
GRANT DROP ANY INDEX TO "ALAIN" ;
GRANT RESTRICTED SESSION TO "ALAIN" ;
GRANT DEQUEUE ANY QUEUE TO "ALAIN" ;
GRANT ANALYZE ANY DICTIONARY TO "ALAIN" ;
GRANT ALTER ANY INDEXTYPE TO "ALAIN" ;
GRANT ADMINISTER ANY SQL TUNING SET TO "ALAIN" ;
GRANT CREATE USER TO "ALAIN" ;
GRANT EXECUTE ANY OPERATOR TO "ALAIN" ;
GRANT CREATE CUBE BUILD PROCESS TO "ALAIN" ;
GRANT CREATE PROFILE TO "ALAIN" ;
GRANT ALTER ANY ROLE TO "ALAIN" ;
GRANT UPDATE ANY TABLE TO "ALAIN" ;
GRANT ALTER ANY LIBRARY TO "ALAIN" ;
GRANT DROP ANY VIEW TO "ALAIN" ;
GRANT CREATE ANY CLUSTER TO "ALAIN" ;
GRANT EXECUTE ANY RULE TO "ALAIN" ;
GRANT ALTER TABLESPACE TO "ALAIN" ;
GRANT UNDER ANY VIEW TO "ALAIN" ;
GRANT EXECUTE ANY ASSEMBLY TO "ALAIN" ;
GRANT GRANT ANY PRIVILEGE TO "ALAIN" ;
GRANT ALTER ANY TRIGGER TO "ALAIN" ;
GRANT CREATE ANY VIEW TO "ALAIN" ;
GRANT EXPORT FULL DATABASE TO "ALAIN" ;
GRANT ALTER ANY EVALUATION CONTEXT TO "ALAIN" ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO "ALAIN" ;
GRANT IMPORT FULL DATABASE TO "ALAIN" ;
GRANT CREATE ANY OUTLINE TO "ALAIN" ;
GRANT COMMENT ANY TABLE TO "ALAIN" ;
GRANT CREATE DATABASE LINK TO "ALAIN" ;
GRANT DROP PUBLIC SYNONYM TO "ALAIN" ;
GRANT DROP USER TO "ALAIN" ;
GRANT CHANGE NOTIFICATION TO "ALAIN" ;
GRANT CREATE MINING MODEL TO "ALAIN" ;
GRANT INSERT ANY TABLE TO "ALAIN" ;
GRANT DROP PROFILE TO "ALAIN" ;
GRANT CREATE ANY MATERIALIZED VIEW TO "ALAIN" ;
GRANT CREATE RULE SET TO "ALAIN" ;
GRANT EXEMPT ACCESS POLICY TO "ALAIN" ;
GRANT MANAGE SCHEDULER TO "ALAIN" ;
GRANT READ ANY FILE GROUP TO "ALAIN" ;
GRANT FORCE TRANSACTION TO "ALAIN" ;
GRANT DROP ANY CUBE BUILD PROCESS TO "ALAIN" ;
GRANT ALTER ANY TYPE TO "ALAIN" ;
GRANT DROP ANY PROCEDURE TO "ALAIN" ;
GRANT DROP PUBLIC DATABASE LINK TO "ALAIN" ;
GRANT DROP ANY INDEXTYPE TO "ALAIN" ;
GRANT DROP ANY SQL PROFILE TO "ALAIN" ;
GRANT ALTER SYSTEM TO "ALAIN" ;
GRANT DROP ANY ROLE TO "ALAIN" ;
GRANT ALTER ANY DIMENSION TO "ALAIN" ;
GRANT DROP ANY CUBE DIMENSION TO "ALAIN" ;
GRANT DROP ANY CUBE TO "ALAIN" ;
GRANT CREATE ANY TRIGGER TO "ALAIN" ;
GRANT DROP ANY ASSEMBLY TO "ALAIN" ;
GRANT CREATE ANY TABLE TO "ALAIN" ;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "ALAIN" ;
GRANT DROP ANY DIRECTORY TO "ALAIN" ;
GRANT ENQUEUE ANY QUEUE TO "ALAIN" ;
GRANT DROP ANY EVALUATION CONTEXT TO "ALAIN" ;
GRANT CREATE ANY ASSEMBLY TO "ALAIN" ;
GRANT CREATE ANY TYPE TO "ALAIN" ;
GRANT CREATE CLUSTER TO "ALAIN" ;
GRANT CREATE ANY CONTEXT TO "ALAIN" ;
GRANT EXECUTE ANY EVALUATION CONTEXT TO "ALAIN" ;
GRANT RESUMABLE TO "ALAIN" ;
GRANT CREATE ANY LIBRARY TO "ALAIN" ;
GRANT DROP ANY EDITION TO "ALAIN" ;
GRANT CREATE PROCEDURE TO "ALAIN" ;
GRANT ALTER DATABASE TO "ALAIN" ;
GRANT SELECT ANY CUBE TO "ALAIN" ;
GRANT GRANT ANY ROLE TO "ALAIN" ;
GRANT ALTER ANY RULE TO "ALAIN" ;
GRANT CREATE CUBE DIMENSION TO "ALAIN" ;
GRANT ALTER ANY OPERATOR TO "ALAIN" ;
GRANT CREATE CUBE TO "ALAIN" ;
GRANT ALTER RESOURCE COST TO "ALAIN" ;
GRANT DROP TABLESPACE TO "ALAIN" ;
GRANT ALTER ROLLBACK SEGMENT TO "ALAIN" ;

--CREATE A TEST TABLE
  CREATE TABLE ALAIN.U_test
   (	z_test_id NUMBER(*,0)
   ) 
  TABLESPACE ALAIN_SPACE ;
  
  
