--CREATE A NEW PERSONAL alain_space TABLESPACE 
CREATE TABLESPACE alain_space
DATAFILE '\opt\oracle\oradata\FREE\alain_space.dbf'
SIZE 50m;

--CHECK IF TABLE_SPACE HAS BEEN CREATED
SELECT * FROM SYS.DBA_DATA_FILES WHERE TABLESPACE_NAME LIKE '%ALAIN%';

-- CREATE USER 1 SQL ON THE TABLESPACE "ALAIN_SPACE"
CREATE USER "ALAIN" IDENTIFIED BY alain
DEFAULT TABLESPACE "ALAIN_SPACE"
TEMPORARY TABLESPACE "TEMP"
ENABLE EDITIONS ;

-- QUOTAS
ALTER USER "ALAIN" QUOTA UNLIMITED ON "ALAIN_SPACE";
ALTER USER "ALAIN" QUOTA UNLIMITED ON "USERS";
-- ROLES
GRANT "DV_MONITOR" TO "ALAIN" ;
GRANT "SHARDED_SCHEMA_OWNER" TO "ALAIN" ;
GRANT "WM_ADMIN_ROLE" TO "ALAIN" ;
GRANT "OLAP_USER" TO "ALAIN" ;
GRANT "DV_SECANALYST" TO "ALAIN" ;
GRANT "MAINTPLAN_APP" TO "ALAIN" ;
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "ALAIN" ;
GRANT "AVTUNE_PKG_ROLE" TO "ALAIN" ;
GRANT "GDS_CATALOG_SELECT" TO "ALAIN" ;
GRANT "PGX_SESSION_GET_PUBLISHED_GRAPH" TO "ALAIN" ;
GRANT "SCHEDULER_ADMIN" TO "ALAIN" ;
GRANT "PROVISIONER" TO "ALAIN" ;
GRANT "PGX_SERVER_GET_INFO" TO "ALAIN" ;
GRANT "APPLICATION_TRACE_VIEWER" TO "ALAIN" ;
GRANT "LBAC_DBA" TO "ALAIN" ;
GRANT "OSAK_ADMIN_ROLE" TO "ALAIN" ;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "ALAIN" ;
GRANT "GSMUSER_ROLE" TO "ALAIN" ;
GRANT "GATHER_SYSTEM_STATISTICS" TO "ALAIN" ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "ALAIN" ;
GRANT "DBJAVASCRIPT" TO "ALAIN" ;
GRANT "GSM_POOLADMIN_ROLE" TO "ALAIN" ;
GRANT "HS_ADMIN_ROLE" TO "ALAIN" ;
GRANT "OGG_APPLY" TO "ALAIN" ;
GRANT "XS_SESSION_ADMIN" TO "ALAIN" ;
GRANT "GSMCATUSER_ROLE" TO "ALAIN" ;
GRANT "JAVADEBUGPRIV" TO "ALAIN" ;
GRANT "CONNECT" TO "ALAIN" ;
GRANT "SQL_FIREWALL_ADMIN" TO "ALAIN" ;
GRANT "ACCHK_READ" TO "ALAIN" ;
GRANT "PGX_SESSION_READ_MODEL" TO "ALAIN" ;
GRANT "SQL_FIREWALL_VIEWER" TO "ALAIN" ;
GRANT "SODA_APP" TO "ALAIN" ;
GRANT "BDSQL_ADMIN" TO "ALAIN" ;
GRANT "PGX_SESSION_NEW_GRAPH" TO "ALAIN" ;
GRANT "GSMADMIN_ROLE" TO "ALAIN" ;
GRANT "GRAPH_DEVELOPER" TO "ALAIN" ;
GRANT "JAVAUSERPRIV" TO "ALAIN" ;
GRANT "XDB_SET_INVOKER" TO "ALAIN" ;
GRANT "JAVA_ADMIN" TO "ALAIN" ;
GRANT "DBFS_ROLE" TO "ALAIN" ;
GRANT "PDB_DBA" TO "ALAIN" ;
GRANT "RDFCTX_ADMIN" TO "ALAIN" ;
GRANT "CDB_DBA" TO "ALAIN" ;
GRANT "JAVASYSPRIV" TO "ALAIN" ;
GRANT "GSMROOTUSER_ROLE" TO "ALAIN" ;
GRANT "HS_ADMIN_SELECT_ROLE" TO "ALAIN" ;
GRANT "AUDIT_VIEWER" TO "ALAIN" ;
GRANT "RESOURCE" TO "ALAIN" ;
GRANT "DV_OWNER" TO "ALAIN" ;
GRANT "OGG_CAPTURE" TO "ALAIN" ;
GRANT "EXP_FULL_DATABASE" TO "ALAIN" ;
GRANT "OGG_APPLY_PROCREP" TO "ALAIN" ;
GRANT "PGX_SESSION_ADD_PUBLISHED_GRAPH" TO "ALAIN" ;
GRANT "CAPTURE_ADMIN" TO "ALAIN" ;
GRANT "OEM_ADVISOR" TO "ALAIN" ;
GRANT "OGG_SHARED_CAPTURE" TO "ALAIN" ;
GRANT "DBA" TO "ALAIN" ;
GRANT "PPLB_ROLE" TO "ALAIN" ;
GRANT "CTXAPP" TO "ALAIN" ;
GRANT "DV_AUDIT_CLEANUP" TO "ALAIN" ;
GRANT "OLAP_XS_ADMIN" TO "ALAIN" ;
GRANT "XS_CACHE_ADMIN" TO "ALAIN" ;
GRANT "GRAPH_USER" TO "ALAIN" ;
GRANT "DB_DEVELOPER_ROLE" TO "ALAIN" ;
GRANT "AUDIT_ADMIN" TO "ALAIN" ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "ALAIN" ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "ALAIN" ;
GRANT "SYSUMF_ROLE" TO "ALAIN" ;
GRANT "DATAPUMP_CLOUD_IMP" TO "ALAIN" ;
GRANT "XDB_WEBSERVICES" TO "ALAIN" ;
GRANT "OPTIMIZER_PROCESSING_RATE" TO "ALAIN" ;
GRANT "RECOVERY_CATALOG_USER" TO "ALAIN" ;
GRANT "DV_ADMIN" TO "ALAIN" ;
GRANT "DV_POLICY_OWNER" TO "ALAIN" ;
GRANT "DV_GOLDENGATE_ADMIN" TO "ALAIN" ;
GRANT "IMP_FULL_DATABASE" TO "ALAIN" ;
GRANT "DV_XSTREAM_ADMIN" TO "ALAIN" ;
GRANT "DV_PATCH_ADMIN" TO "ALAIN" ;
GRANT "GGSYS_ROLE" TO "ALAIN" ;
GRANT "NOTIFICATIONS_USER" TO "ALAIN" ;
GRANT "XSTREAM_APPLY" TO "ALAIN" ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ALAIN" ;
GRANT "EJBCLIENT" TO "ALAIN" ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "ALAIN" ;
GRANT "JMXSERVER" TO "ALAIN" ;
GRANT "OLAP_DBA" TO "ALAIN" ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "ALAIN" ;
GRANT "JAVAIDPRIV" TO "ALAIN" ;
GRANT "SELECT_CATALOG_ROLE" TO "ALAIN" ;
GRANT "DGPDB_ROLE" TO "ALAIN" ;
GRANT "PGX_SESSION_MODIFY_MODEL" TO "ALAIN" ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ALAIN" ;
GRANT "OEM_MONITOR" TO "ALAIN" ;
GRANT "PGX_SERVER_MANAGE" TO "ALAIN" ;
GRANT "GRAPH_ADMINISTRATOR" TO "ALAIN" ;
GRANT "AQ_USER_ROLE" TO "ALAIN" ;
GRANT "RECOVERY_CATALOG_OWNER" TO "ALAIN" ;
GRANT "DATAPUMP_CLOUD_EXP" TO "ALAIN" ;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "ALAIN" ;
GRANT "XSTREAM_CAPTURE" TO "ALAIN" ;
GRANT "SAGA_CONNECT_ROLE" TO "ALAIN" ;
GRANT "SAGA_PARTICIPANT_ROLE" TO "ALAIN" ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "ALAIN" ;
GRANT "EXECUTE_CATALOG_ROLE" TO "ALAIN" ;
GRANT "DV_ACCTMGR" TO "ALAIN" ;
GRANT "NOTIFICATIONS_ADMIN" TO "ALAIN" ;
GRANT "SAGA_ADM_ROLE" TO "ALAIN" ;
GRANT "PGX_SESSION_CREATE" TO "ALAIN" ;
GRANT "DBMS_MDX_INTERNAL" TO "ALAIN" ;
GRANT "DV_STREAMS_ADMIN" TO "ALAIN" ;
GRANT "XS_NAMESPACE_ADMIN" TO "ALAIN" ;
GRANT "BDSQL_USER" TO "ALAIN" ;
GRANT "AUTHENTICATEDUSER" TO "ALAIN" ;
GRANT "XS_CONNECT" TO "ALAIN" ;
GRANT "XDBADMIN" TO "ALAIN" ;
GRANT "PGX_SESSION_COMPILE_ALGORITHM" TO "ALAIN" ;
