--SEEL ALL TABLES
SELECT * FROM all_tables;

--SEE ALL PLUGGABLES DTB
SELECT * FROM v$pdbs;

--SEE ALL USERS
SELECT * FROM dba_users;
SELECT * FROM all_users;


--CONNECTED USER
SHOW USER;
--SEE CURRENT CONNECTION
SHOW con_name;

--UNLOCK USER
ALTER USER "HR" IDENTIFIED BY oracle ACCOUNT UNLOCK;

--GRANT ALL PRIVILEGES
GRANT ALL PRIVILEGES TO "HR";

--CREATE USER
alter session set container;
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER alain IDENTIFIED BY alain;